// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestTask.dal;

#nullable disable

namespace TestTask.Migrations
{
    [DbContext(typeof(BillingContext))]
    partial class BillingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("TestTask.dal.Models.Bill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("ColdWaterCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("ElectricityCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("ElectricityDayCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("ElectricityNightCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("HotWaterCharge")
                        .HasColumnType("REAL");

                    b.Property<double>("HotWaterHeatCharge")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Total")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("TestTask.dal.Models.MonthlyReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<double>("Current")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<double>("Previous")
                        .HasColumnType("REAL");

                    b.Property<int>("Service")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("MonthlyReadings");
                });

            modelBuilder.Entity("TestTask.dal.Models.ResidentCount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Count")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("From")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Month")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("To")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("ResidentCounts");
                });

            modelBuilder.Entity("TestTask.dal.Models.ServiceNorm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Service", "EffectiveFrom");

                    b.ToTable("Norms");
                });

            modelBuilder.Entity("TestTask.dal.Models.ServiceTariff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("TEXT");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Service", "EffectiveFrom");

                    b.ToTable("Tariffs");
                });

            modelBuilder.Entity("TestTask.dal.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("TestTask.dal.Models.Bill", b =>
                {
                    b.HasOne("TestTask.dal.Models.Tenant", null)
                        .WithMany("Bills")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestTask.dal.Models.MonthlyReading", b =>
                {
                    b.HasOne("TestTask.dal.Models.Tenant", null)
                        .WithMany("MonthlyReadings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestTask.dal.Models.ResidentCount", b =>
                {
                    b.HasOne("TestTask.dal.Models.Tenant", null)
                        .WithMany("ResidentCounts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TestTask.dal.Models.Tenant", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("MonthlyReadings");

                    b.Navigation("ResidentCounts");
                });
#pragma warning restore 612, 618
        }
    }
}
